### ISSUE TITLE
Exception when MAPQ unmapped read != 0

### ISSUE THREAD

**Issue by ryanlayer** [rdemolgen/SavvySuite#3]
While this should be true, in the set of bams I have it is not. Can you catch this exception so that I do not have to fix the bams?

Thanks! 

Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 52890647, Read name JDQNNM1:113:D0VJBACXX:1:1311:14032:7891, MAPQ should be 0 for unmapped read.
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:451)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:812)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
        at CoverageBinner.main(CoverageBinner.java:25)

**Comment by exeter-matthew-wakeling** [comment]
Please could you check that this fixes your problem and let me know in a comment in this issue.

Thanks

**Comment by ryanlayer** [comment]
Ignoring SAM validation error: ERROR: Record 15390807, Read name JDQNNM1:123:D1HCGACXX:5:1209:6625:68819, MAPQ should be 0 for unmapped read.

Looks great. Thanks
