### ISSUE TITLE
Can't compile latest version

### ISSUE THREAD

**Issue by oleraj** [rdemolgen/SavvySuite#5]
Hi,

I see you made some improvements to SavvyHomozygosity (and others) so I would like to try them out.  However, I can't get this one to compile for some reason...

```
echo $CLASSPATH
/Apps/SavvySuite/SavvySuite-master-2017-12-22:/software/GATK/3.5-0-Java-1.7.0_80/GenomeAnalysisTK.jar
javac *.java
Picked up _JAVA_OPTIONS: -Xmx1G
PrepareLinkageData.java:94: error: cannot find symbol
		private TreeMap<Integer, VariantArray> variantsInFlight = new TreeMap<Integer, VariantArray>();
		                         ^
  symbol:   class VariantArray
  location: class Output
PrepareLinkageData.java:103: error: cannot find symbol
		public void add(VariantArray context) throws IOException {
		                ^
  symbol:   class VariantArray
  location: class Output
PrepareLinkageData.java:125: error: cannot find symbol
		public void outputContext(VariantArray context) throws IOException {
		                          ^
  symbol:   class VariantArray
  location: class Output
SavvySharedHaplotypes.java:120: error: cannot find symbol
	public static void createSignal(int wildCount, int varCount, TreeMap<Integer, Boolean> storedBases, TreeMap<Integer, VariantArray> storedVariants, VariantArray vArray, Viterbi viterbi, double negativeMultiplier, String currentChr) {
	                                                                                                                     ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:120: error: cannot find symbol
	public static void createSignal(int wildCount, int varCount, TreeMap<Integer, Boolean> storedBases, TreeMap<Integer, VariantArray> storedVariants, VariantArray vArray, Viterbi viterbi, double negativeMultiplier, String currentChr) {
	                                                                                                                                                   ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
PrepareLinkageData.java:47: error: cannot find symbol
		TreeMap<Integer, VariantArray> storedVariants = null;
		                 ^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:53: error: cannot find symbol
				storedVariants = new TreeMap<Integer, VariantArray>();
				                                      ^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:71: error: cannot find symbol
					VariantArray vArray = new VariantArray(vcfSampleNames, context);
					^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:71: error: cannot find symbol
					VariantArray vArray = new VariantArray(vcfSampleNames, context);
					                          ^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:72: error: cannot find symbol
					Iterator<Map.Entry<Integer, VariantArray>> storedIter = storedVariants.entrySet().iterator();
					                            ^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:74: error: cannot find symbol
						Map.Entry<Integer, VariantArray> storedEntry = storedIter.next();
						                   ^
  symbol:   class VariantArray
  location: class PrepareLinkageData
PrepareLinkageData.java:94: error: cannot find symbol
		private TreeMap<Integer, VariantArray> variantsInFlight = new TreeMap<Integer, VariantArray>();
		                                                                               ^
  symbol:   class VariantArray
  location: class Output
PrepareLinkageData.java:118: error: cannot find symbol
			for (Map.Entry<Integer, VariantArray> entry : variantsInFlight.entrySet()) {
			                        ^
  symbol:   class VariantArray
  location: class Output
SavvyHomozygosity.java:51: error: cannot find symbol
		TreeMap<Integer, VariantArray> storedVariants = null;
		                 ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:56: error: cannot find symbol
		VariantArray vArray = null;
		^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:58: error: cannot find symbol
			vArray = (VariantArray) vcf.readObject();
			          ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:68: error: cannot find symbol
				storedVariants = new TreeMap<Integer, VariantArray>();
				                                      ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:91: error: cannot find symbol
					Iterator<Map.Entry<Integer, VariantArray>> storedIter = storedVariants.entrySet().iterator();
					                            ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:93: error: cannot find symbol
						Map.Entry<Integer, VariantArray> storedEntry = storedIter.next();
						                   ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvyHomozygosity.java:117: error: cannot find symbol
				vArray = (VariantArray) vcf.readObject();
				          ^
  symbol:   class VariantArray
  location: class SavvyHomozygosity
SavvySharedHaplotypes.java:42: error: cannot find symbol
		TreeMap<Integer, VariantArray> storedVariants = null;
		                 ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:44: error: cannot find symbol
		TreeMap<Integer, VariantArray> storedVariants2 = null;
		                 ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:49: error: cannot find symbol
		VariantArray vArray = null;
		^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:51: error: cannot find symbol
			vArray = (VariantArray) vcf.readObject();
			          ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:61: error: cannot find symbol
				storedVariants = new TreeMap<Integer, VariantArray>();
				                                      ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:66: error: cannot find symbol
					storedVariants2 = new TreeMap<Integer, VariantArray>();
					                                       ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:110: error: cannot find symbol
				vArray = (VariantArray) vcf.readObject();
				          ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:129: error: cannot find symbol
		Iterator<Map.Entry<Integer, VariantArray>> storedIter = storedVariants.entrySet().iterator();
		                            ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
SavvySharedHaplotypes.java:131: error: cannot find symbol
			Map.Entry<Integer, VariantArray> storedEntry = storedIter.next();
			                   ^
  symbol:   class VariantArray
  location: class SavvySharedHaplotypes
29 errors
```
I think this is the same version of Java and GATK that I used to compile the previous version I had downloaded so I'm not sure what has changed.

Thanks,

Andrew

**Comment by exeter-matthew-wakeling** [comment]
Ah, yes, sorry, my mistake. I forgot to add a file when I updated SavvyHomozygosity and SavvySharedHaplotypes (they take a minute instead of an hour to run now). Should be all fixed now. SavvyCNV also has improved sensitivity/specificity due to a more realistic error model.

If you find this software useful, please do let me know. I'm just in the process of writing papers to cover it - should be published Real Soon Now (tm).

**Comment by exeter-matthew-wakeling** [comment]
Should be fixed.

**Comment by oleraj** [comment]
Thanks, it compiles now.  However, I'm getting an error message when I try to run it:
```
java -Xmx5g SavvyHomozygosity 400.wgs.phase3.20130502.genotypes.concat.vcf.gz $bam > ${s}.${ESGS}.SavvyHom.new.400g.bed
Picked up _JAVA_OPTIONS: -Xmx1G
Exception in thread "main" java.io.StreamCorruptedException: invalid stream header: 1F8B0804
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at SavvyHomozygosity.main(SavvyHomozygosity.java:49)
```
Any ideas?

**Comment by exeter-matthew-wakeling** [comment]
Hi.

I changed the way SavvyHomozygosity works a few months ago, and updated the main README, but didn't otherwise advertise it. You need to convert your VCF file into a binary format file that is quicker to load and process (loading a similar vcf on our server takes about an hour, compared to seven seconds to load the binary file). This improves the speed of processing a bit. So, you need to run:

```
java -Xmx5g PrepareLinkageData 400.wgs.phase3.20130502.genotypes.concat.vcf.gz >linkage_data
```

This only needs to be done once. You can then run:

```
java -Xmx5g SavvyHomozygosity linkage_data $bam > ${s}.${ESGS}.SavvyHom.new.400g.bed
```

Also, I haven't checked whether the VCF-reading library I am using will automatically read a bgzipped VCF file - it might just magically work, but if not then decompress it and index it first.

Hope this helps. Let me know if all is well.

**Comment by oleraj** [comment]
Yes, that works now thanks.
